# Generated by Django 5.2.4 on 2025-08-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='valor_gasto_total',
        ),
    ]
