# Generated by Django 5.2.4 on 2025-08-04 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_rename_servicos_que_executa_funcionario_servico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_horario', models.DateTimeField(verbose_name='Data')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data_agendamento',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='servicos',
        ),
        migrations.CreateModel(
            name='ServicoFuncionarioHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamento.datahorario', verbose_name='Data')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamento.funcionario', verbose_name='Funcionario')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamento.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Vaga de Atendimento',
                'verbose_name_plural': 'Vagas de Atendimento',
                'unique_together': {('funcionario', 'servico', 'data_horario')},
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico_funcionario_horario',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='agendamento.servicofuncionariohorario', verbose_name='Vaga de Atendimento'),
        ),
    ]
