# Generated by Django 5.2.4 on 2025-08-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_datahorario_remove_agendamento_data_agendamento_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicofuncionariohorario',
            unique_together={('funcionario', 'data_horario')},
        ),
        migrations.RemoveField(
            model_name='servicofuncionariohorario',
            name='servico',
        ),
        migrations.AddField(
            model_name='servicofuncionariohorario',
            name='servico',
            field=models.ManyToManyField(to='agendamento.servico', verbose_name='Serviço(s)'),
        ),
    ]
