# Generated by Django 5.2.4 on 2025-08-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_alter_servicofuncionariohorario_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(help_text='Digite o número do celular dentro do padrão (XX) XXXXX-XXXX', max_length=15, verbose_name='Celular com DDD'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(help_text='Digite o cpf dentro do padrão XXX.XXX.XXX-XX', max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
