# Generated by Django 5.2.4 on 2025-08-05 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_alter_pessoa_options_alter_pessoa_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='O número de celular deve estar no formato: (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')], verbose_name='Celular com DDD'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve estar no formato: XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF'),
        ),
    ]
